### ISSUE TITLE
Version Management - Composer

### ISSUE THREAD

**Issue by CadenceLabs-AndrewS** [helloextend/magento-extension#187]
It would be very much appreciated if this module would be released with proper versioning in composer so that we can update to a specific **stable** version.

The current method using 'dev-master' and having the lock reference the latest commit does not seem proper.

**Comment by lporter-extend** [comment]
@CadenceLabs-AndrewS thank you for reporting this issue. Version tags are now part of our release process for the module. For a full list of releases, please see: https://github.com/helloextend/magento-extension/releases
