### ISSUE TITLE
Virtual type - source file doesn't exist, indexer fails

### ISSUE THREAD

**Issue by molinainat** [helloextend/magento-extension#226]
var/log/exeption.log error:
`report.CRITICAL: Class Extend\Warranty\Model\ResourceModel\Indexer\Price does not exist {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Class Extend\\Warranty\\Model\\ResourceModel\\Indexer\\Price does not exist`

etc/di.xml:35-37
`<virtualType
            name="Extend\Warranty\Model\ResourceModel\Indexer\Price"
            type="Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\DefaultPrice"/>`

**Comment by lastralab** [comment]
Not an authorized user but here's the PR: https://github.com/helloextend/magento-extension/pull/227
