### ISSUE TITLE
Composer.json and PHP 8.2

### ISSUE THREAD

**Issue by bentideswell** [helloextend/magento-extension#392]
Does this module support PHP 8.2? I'm trying to use this on a Magento 2.4.6 installation with PHP 8.2 but your composer.json file limits the PHP version to 8.1 and below.

**Comment by lporter-extend** [comment]
Hello Ben, we have not validated this module works fully with PHP 8.2 hence the limit to 8.1 and below. Can you reach out to me at logan@extend.com and let me know which Extend merchant partner you are working with? That will help us better understand how we can support you.

**Comment by bentideswell** [comment]
Thanks Logan. I've just sent you an email.

**Comment by lporter-extend** [comment]
Resolved in https://github.com/helloextend/magento-extension/pull/393

Release: https://github.com/helloextend/magento-extension/releases/tag/v2.2.3
